sudo: false
dist: trusty
language: cpp
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
      sonarcloud:
        organization: "sylvie-github" # the key of the org you chose at step #3
        token:
          secure: ${SONAR_TOKEN} # encrypted value of your token
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && export GCOV=gcov-7"
      - SAMBADA_OS_NAME=ubuntu
      - SAMBADA_BUILD_TYPE=CODE_COVERAGE
      - CXXFLAGS="-std=c++11 -Wall --coverage"
      - LDFLAGS=-static
      - CC_TEST_REPORTER_ID=a255dacf87a9616a60330b2959945e4e670e0857056d34dae0a9408bf54103c0
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    install:
      - source ./manual/texlive-ubuntu.sh
    cache:
      directories:
      - "/tmp/texlive"
      - "$HOME/.texlive"
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      - SAMBADA_OS_NAME=ubuntu
      - SAMBADA_BUILD_TYPE=PACKAGE
      - CXXFLAGS="-std=c++11 -Wall -O2"
      - LDFLAGS=-static
  - os: osx
    osx_image: xcode10.1
    compiler: gcc
    env:
      - MATRIX_EVAL="softwareupdate -l && sudo softwareupdate -i \"Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4\" && brew install gcc@7 && CC=gcc-7 && CXX=g++-7"
      - SAMBADA_OS_NAME=${TRAVIS_OS_NAME}
      - SAMBADA_BUILD_TYPE=PACKAGE
      - CXXFLAGS="-std=c++11 -Wall -O2"
    install:
      - source ./manual/basictex-osx.sh
      - ls -la /usr/local/texlive/
      - ls -l /Library/PreferencePanes
    cache:
      directories:
        - "/usr/local/texlive/"
        - "/usr/local/bin/texdist/"
        - "/usr/texbin/"
        - "/Library/TeX/"
        - "/Library/PreferencePanes/"

before_install:
  - eval "${MATRIX_EVAL}"
git:
  depth: 100
script: ./scripts-ci/travis-build.sh

after_failure:
  - cat test-suite-results.log

before_deploy:
  - sambada_version=$(./git-version-gen .version)

deploy:
  provider: releases
  api_key:
    secure: CzbfMbZGdbn0y6mATV2wN8trTAmJ6QHvXI7LxLjV4P45v3/9fAKD/nXM49xdxnhv+FZZ56mW9qi42FrHzYk/n5f73kHqgpKyRyVIiox5wtgQH/de4J0N1gmR8BbP8bC7v3k2pfKwbtcKcWDtmrnpnb86XJe9XZ2wSaD1Tetifb/uZC8SIdf9X0pxcnfFcG3+Rg0Dvvn7YQ0M1yDXtMZ0AdOICQ2HxfGz+x/rMvC0hE+qY0T3a7LqFA6+gOaV9cP8SfbM9ZSvT5Von8VibTZOD78HF+PEZg4CCE99zvW4iO2VfnQWmMgIUTE6yIrE8G3rxCTWWRX8H91PLVSE+RWNFYaNbLeXTkapuWsLLRR+PLDhgE/H+gBUcji3XcSwUrG7M8QAfuzhv1aiS/p7WvhE/3CXU2SkhllQTi6/PWcJn9MmTd2NCFJEkuy0L6Jo+lw+dKbztt2kMol6pM2fjByf5XThhuPjGX81cVX2iGpbHBqL0agiSkLUybwPevJcAKS8UKJPkFRsCe+Nwt9iPm8R/ZdUOQW/0PJYLDBSuB8nalnEhlqik5BJ4T/9fIu24Hc8SyiI/PZ5ZxMPmuMkuBhAs5NcO/Mae82Ugvuj5zBtSvD5RMx1fMKuG4eyhtgbI9vsSgpKWduRGkyxZp9tysgaCWcrYSsSyGv/HO2shp2Fn6w=
  file:
    - build/sambada-${sambada_version}-${SAMBADA_OS_NAME}.tar.gz
    - build/sambada-${sambada_version}.tar.gz
    - build/sambada-${sambada_version}.zip
    - build/manual/sambadoc.pdf
  skip_cleanup: true
  draft: false
  on:
    repo: Sylvie/sambada
    tags: true
    condition: ${SAMBADA_BUILD_TYPE} = PACKAGE
