# Use new trusty images, should yield newer compilers and packages
sudo: false          # false (Docker) or required (own VM)
dist: precise
language: generic

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - os: osx
      compiler: gcc
      env: COMPILER=g++

git:
  depth: 100

script:
  - autoreconf -i
  - sambada_version=$(./git-version-gen .version)
  - mkdir build
  - cd build
  - ../configure sambadahostsystemname=${TRAVIS_OS_NAME}
  - make CXX=$COMPILER
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then make distcheck; fi
  - ls -R
  - binaries/sambada Data/Example_parameters_input_matrix.txt Data/input_matrix.csv
