# Use new trusty images, should yield newer compilers and packages
sudo: false          # false (Docker) or required (own VM)
dist: trusty
language: generic

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      install:
        - source ./manual/texlive-ubuntu.sh
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive
      env: COMPILER=g++-5
    - os: osx
      compiler: gcc
      env: COMPILER=g++
      install:
        - source ./manual/basictex-osx.sh
        - ls /usr/local/texlive/
        - ls -l /Library/PreferencePanes
      cache:
        directories:
          - /usr/local/texlive/
          - /usr/local/bin/texdist/
          - /usr/texbin/
          - /Library/TeX/
          - /Library/PreferencePanes/

git:
  depth: 100

script:
  - autoreconf -i
  - sambada_version=$(./git-version-gen .version)
  - mkdir build
  - cd build
  - ../configure sambadahostsystemname=${TRAVIS_OS_NAME}
  - make pdf
  - make CXX=$COMPILER
  - binaries/sambada ../Data/Example_parameters_input_matrix.txt ../Data/input_matrix.csv
  - ls -R
  - make distcheck
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then make dist; fi
  - cd ..
