#---------------------------------#
#    environment configuration    #
#---------------------------------#
# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# build cache to preserve files/folders between builds
cache:
#  - C:\ProgramData\chocolatey\bin -> appveyor.yml
#  - C:\ProgramData\chocolatey\lib -> appveyor.yml
#  - C:\Program Files\MiKTeX 2.9 -> appveyor.yml
#  - C:\Users\appveyor\AppData\Roaming\MiKTeX\2.9 -> appveyor.yml

# scripts that run after cloning repository
install:
#  - ps: choco install miktex
#  - SET PATH=C:\Program Files\MiKTeX 2.9\miktex\bin\x64;%PATH%
#  - ps: initexmf --admin --set-config-value [MPM]AutoInstall=1

#---------------------------------#
#       build configuration       #
#---------------------------------#
# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: windows

build_script:
  - SET PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\x86_64-w64-mingw32;
  - ps: $env:sambada_version=(bash -c './git-version-gen .version')
  - bash -c "autoreconf -i"
  - mkdir build
  - cd build
  - bash -c "../configure sambadahostsystemname=%PLATFORM% --host=x86_64-w64-mingw32 CXXFLAGS=\"-O2\" LDFLAGS=\"-static\" --disable-manual"
  - make pdf
  - make.exe
  - ls -R binaries
  - ps: .\binaries\sambada.exe ..\Data\Example_parameters_input_matrix.txt ..\Data\input_matrix.csv
  - make.exe dist DIST_TARGETS=dist-gzip
  - make binary-archive
  - ls -R

#---------------------------------#
#       tests configuration       #
#---------------------------------#
# to run your custom scripts instead of automatic tests
test_script:
  - Measure-Command {make check}
  - cp test-suite.log ../test-suite-results.log
  - ls -R
  - make.exe clean
  - make.exe DISTCHECK_CONFIGURE_FLAGS="sambadahostsystemname=%PLATFORM% --host=x86_64-w64-mingw32 CXXFLAGS=\"-O2\" LDFLAGS=\"-static\"  --disable-manual" distcheck DIST_TARGETS=dist-gzip

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:

# pushing entire folder as a zip archive
  - path: build\sambada-$(sambada_version)-%PLATFORM%

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    auth_token:
      secure: /nU7mUteW5yQE7WTvX8WQmsR2/qhQr5p34xBndoB9YfP1pTTLxjFdem3OAsMexyR
    draft: false
    prerelease: true
    on:
      appveyor_repo_tag: true       # deploy on tag push only

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
#on_success:
#- do something

# on build failure
on_failure:
  - ps: if (Test-Path test-suite.log) { cat test-suite.log }
  - ps: if (Test-Path ../test-suite-results.log) { cat ../test-suite-results.log }
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# after build failure or success
#on_finish:
#- do something
