name: Sambada Build

on:
  push:
    paths-ignore:
    - '.github/workflows/verification.yml'
  pull_request:

env:
  CC: gcc-11
  CXX: g++-11

jobs:
  workflow-params:
    name: Determining workflow params
    runs-on: macos-10.15
    outputs:
      version-number: ${{ steps.version-number.outputs.sambada_version_number }}
    steps:
      - name: Greetings
        run: |
          echo "Hello!"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetching all tags
        run: |
          git fetch --tags --force
      - name: determine version number
        id: version-number
        run: |
          echo "----------------------------------------------"
          git tag
          echo "----------------------------------------------"
          git describe
          echo "----------------------------------------------"
          sambada_version_number=$(./git-version-gen .version)
          echo "----------------------------------------------"
          echo ${sambada_version_number}
          echo "----------------------------------------------"
          echo "::set-output name=sambada_version_number::${sambada_version_number}"

  read-params:
    name: Reading workflow params
    runs-on: ubuntu-latest
    needs: workflow-params
    env:
      sambada_version_number: ${{ needs.workflow-params.outputs.version-number }}

    steps:
      - name: Greetings
        run: |
          echo "Hello!"
          echo "Reading output: ${{ needs.workflow-params.outputs.version-number }}"
      - name: Read variables
        run: |
          echo "${sambada_version_number}"

  build:
    name: Building
    runs-on: macos-10.15
    needs: workflow-params
    env:
      sambada_version_number: ${{ needs.workflow-params.outputs.version-number }}
    strategy:
      matrix:
        build-type: [ package, distcheck ]

    steps:
      - name: Checking out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetching all tags
        run: |
          git fetch --tags --force

      - name: Installing missing package
        run: |
          brew install automake

      - name: Configuring
        run: |
          autoreconf -i
          mkdir build
          cd build
          ../configure --disable-manual

      - name: Building
        if: ${{ matrix.build-type == 'package' }}
        env:
          sambada_version: ${{ steps.version-number.outputs.sambada_version }}
        run: |
          cd build
          make

      - name: Running check
        if: ${{ matrix.build-type == 'package' }}
        run: |
          cd build
          make check
          cat test-suite.log

      - name: Uploading test results
        if: ${{ matrix.build-type == 'package' && failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-suite-${{ runner.os }}.log
          path: build/test-suite.log
          if-no-files-found: error

      - name: Making archive
        if: ${{ matrix.build-type == 'package' }}
        env:
          sambada_version: ${{ steps.version-number.outputs.sambada_version }}
        run: |
          cd build
          make binary-archive
          ls

      - name: Uploading archive
        if: ${{ matrix.build-type == 'package' }}
        uses: actions/upload-artifact@v2
        with:
          name: sambada-archive-${{ runner.os }}.tar.gz
          path: build/sambada-${{ env.sambada_version_number }}-OSX.tar.gz
          if-no-files-found: error

      - name: Running distcheck
        if: ${{ matrix.build-type == 'distcheck' }}
        env:
          sambada_version: ${{ steps.version-number.outputs.sambada_version }}
        run: |
          cd build
          make distcheck

      - name: Uploading source archive (.zip)
        if: ${{ matrix.build-type == 'distcheck' }}
        uses: actions/upload-artifact@v2
        with:
          name: dist-zip.zip
          path: build/sambada-${{ env.sambada_version_number }}.zip
          if-no-files-found: error

      - name: Uploading source archive (.tar.gz)
        if: ${{ matrix.build-type == 'distcheck' }}
        uses: actions/upload-artifact@v2
        with:
          name: dist-tgz.tar.gz
          path: build/sambada-${{ env.sambada_version_number }}.tar.gz
          if-no-files-found: error

  sambadoc:
    if: false
    name: Compiling Sambada's manual
    runs-on: ubuntu-latest
    needs: workflow-params
    env:
      sambada_version_number: ${{ needs.workflow-params.outputs.version-number }}
      CC: gcc-10
      CXX: g++-10

    steps:

      - name: Checking out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetching all tags
        run: |
          git fetch --tags --force

      - name: Installing missing package
        run: |
          brew install automake

      - name: Configuring build
        run: |
          autoreconf -i
          mkdir build
          cd build
          ../configure

      - name: Preparing LaTeX compilation
        run: |
          cd build
          make manual/latexmkrc

      - name: Compiling LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: manual.tex
          working_directory: build/manual/
          args: |
            -jobname=sambadoc

      - name: Uploading manual
        uses: actions/upload-artifact@v2
        with:
          name: sambadoc.pdf
          path: build/manual/sambadoc.pdf
          if-no-files-found: error
