name: Sambada Build

on: [push, pull_request]

env:
  CC: gcc-11
  CXX: g++-11

jobs:
  build:

    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: check environment
        run: |
          gcc -v
          g++ -v
          gcc-11 -v
          g++-11 -v
      - name: configure
        run: |
          autoreconf -i
          ./configure
          mkdir build
      - name: make
        run: |
          cd build
          make
      - name: make check
        run: |
          cd build
          make check
      - name: make distcheck
        run: |
          cd build
          make distcheck
