name: Sambada Build

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: check environment
        run: |
          gcc -v
          g++ -v
          gcc-11 -v
          g++-11 -v
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
