name: Sambada Build

on: [ push, pull_request ]

env:
  CC: gcc-11
  CXX: g++-11

jobs:
  build:

    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: check environment
        run: |
          set -v
          ${CC} -v
          ${CXX} -v
          brew update
          brew install automake
      - name: configure
        run: |
          autoreconf -i
          mkdir build
          cd build
          ../configure --disable-manual
      - name: determine version number
        id: version-number
        run: |
          sambada_version=$(./git-version-gen .version)
          echo '::set-output name={sambada_version}::{${sambada_version}}'
      - name: make
        run: |
          cd build
          make
      - name: make archive
        run: |
          cd build
          export sambada_version=${{steps.version-number.sambada_version}}
          make binary-archive
          ls
      - name: upload archive
          uses: actions/upload-artifact@v2
          with:
            name: sambada-archive
            path: build/sambada-${{steps.version-number.sambada_version}}-OSX.tar.gz
      - name: make check
        run: |
          cd build
          make check
          cat test-suite.log
          binaries/sambada ../Data/Example_parameters_input_matrix.txt ../Data/input_matrix.csv
          binaries/sambada ../examples/data-from-manual/one-data-file/param-combo.txt ../examples/data-from-manual/one-data-file/combo-data.txt
      - name: make distcheck
        run: |
          export sambada_version=${{steps.version-number.sambada_version}}
          mkdir distributionverification
          cd distributionverification
          ../configure --disable-manual
          make distcheck
