name: Sambada Verification

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (= tag)'
        required: true
        default: 'v0.8.3'
env:
  CC: gcc-11
  CXX: g++-11

jobs:
  verifying-sambada-release:
    name: Verifying Sambada release
    runs-on: ubuntu-latest

    steps:
      - name: Setting environment variables
        run: |
          sambada_version=${{ github.event.inputs.version }}
          sambada_OS_name=ubuntu
          echo "Starting verification of Sambada ${sambada_version}"
          echo "sambada_version=${sambada_version}" >> $GITHUB_ENV
          echo "sambada_OS_name=${sambada_OS_name}" >> $GITHUB_ENV
          echo "package_name=sambada-${sambada_version}-${sambada_OS_name}" >> $GITHUB_ENV

      - name: Checking environment
        run: |
          echo "Sambada version: ${{ env.sambada_version }}"
          echo "Sambada OS name: ${{ env.sambada_OS_name }}"
          echo "Sambada package name: ${{ env.package_name }}"

      - name: Downloading package
        run: |
          wget "https://github.com/Sylvie/sambada/releases/download/v${{ env.sambada_version }}/${{ env.package_name }}.tar.gz"
          tar -zxvf $PACKAGE_NAME.tar.gz

      - name: Smoke testing release
        run: |
          cd ${{ env.package_name }}/examples/subset-cattle-SNP
          time ../../binaries/sambada param-cattle.txt cattle-env.csv cattle-mark.txt
          head  cattle-mark-Out-1.txt
