name: Sambada Verification

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (= tag)'
        required: true
        default: 'v0.8.3'
env:
  CC: gcc-11
  CXX: g++-11

jobs:
  verifying-sambada-release:
    name: Verifying Sambada release
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: |
          echo "Hello!"
          echo "Starting verification of Sambada ${{ github.event.inputs.version }}"
          echo "SAMBADA_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "SAMBADA_OS_NAME=ubuntu" >> $GITHUB_ENV
          echo "PACKAGE_NAME=sambada-${SAMBADA_VERSION}-${SAMBADA_OS_NAME}" >> $GITHUB_ENV

      - name: Checking environment
        run: |
          echo "Sambada version: ${{ env.SAMBADA_VERSION }}
          echo "Sambada OS name: ${{ env.SAMBADA_OS_NAME }}
          echo "Sambada package name: ${{ env.PACKAGE_NAME }}

      - name: Downloading package
        run: |
          SAMBADA_VERSION=${{ github.event.inputs.version }}
          SAMBADA_OS_NAME=ubuntu
          PACKAGE_NAME=sambada-${SAMBADA_VERSION}-${SAMBADA_OS_NAME}
          wget "https://github.com/Sylvie/sambada/releases/download/v${SAMBADA_VERSION}/${PACKAGE_NAME}.tar.gz"
          tar -zxvf $PACKAGE_NAME.tar.gz

      - name: Smoke testing release
        run: |
          SAMBADA_VERSION=${{ github.event.inputs.version }}
          SAMBADA_OS_NAME=ubuntu
          PACKAGE_NAME=sambada-${SAMBADA_VERSION}-${SAMBADA_OS_NAME}
          cd ${PACKAGE_NAME}/examples/subset-cattle-SNP
          time ../../binaries/sambada param-cattle.txt cattle-env.csv cattle-mark.txt
          head  cattle-mark-Out-1.txt
